CREATE TABLE `calculos_tcr` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`nomeDevedor` varchar(255),
	`numeroCedula` varchar(100),
	`modalidade` enum('custeio','investimento','comercializacao') NOT NULL,
	`tipoTaxa` enum('pre_fixada','pos_fixada') NOT NULL,
	`valorPrincipal` decimal(18,2) NOT NULL,
	`dataContratacao` timestamp NOT NULL,
	`dataVencimento` timestamp NOT NULL,
	`dataCalculo` timestamp NOT NULL,
	`prazoMeses` int NOT NULL,
	`taxaJurosRemuneratorios` decimal(8,4) NOT NULL,
	`taxaJurosMora` decimal(8,4),
	`taxaMulta` decimal(8,4),
	`fatorPrograma` decimal(12,7),
	`fatorAjuste` decimal(12,7),
	`fatorInflacaoImplicita` decimal(12,7),
	`taxaJm` decimal(8,4),
	`ipcaAcumulado` decimal(8,4),
	`saldoDevedorAtualizado` decimal(18,2),
	`jurosRemuneratoriosCalculados` decimal(18,2),
	`jurosMoraCalculados` decimal(18,2),
	`multaCalculada` decimal(18,2),
	`totalDevido` decimal(18,2),
	`tcrEfetiva` decimal(8,4),
	`conformeLimiteRemuneratorios` enum('sim','nao','atencao') DEFAULT 'sim',
	`conformeLimiteMora` enum('sim','nao','atencao') DEFAULT 'sim',
	`alertasConformidade` text,
	`memoriaCalculo` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `calculos_tcr_id` PRIMARY KEY(`id`)
);
